name    = Finance-Tiller2QIF
version = 0.01
abstract = Convert Tiller CSV exports to QIF
author  = brainbuz@cpan.org
license = GPL_3
copyright_holder = Your Name

[GatherDir]
[PruneCruft]
[ManifestSkip]
[MetaYAML]
[MetaJSON]
[Readme]
[PodWeaver]
[ExecDir]
[ShareDir]
[MakeMaker]
[Manifest]
; [License]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

[Prereqs]
perl = 5.032
Cpanel::JSON::XS = 0
Getopt::Long::Descriptive = 0
Mojo::SQLite = 0
Path::Tiny = 0
Text::CSV = 0
DateTime::Format::Flexible = 0

